version: '3'
services:
  m2t_bot:
    container_name: m2t_bot
    build: .
    image: mail2telegram/bot:dev
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
      - ./docker/app/conf/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/app/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHAN_DISABLE_XDEBUG_WARN=1
      - PHAN_ALLOW_XDEBUG=0
      - PHP_IDE_CONFIG=serverName=app
networks:
  default:
    external:
      name: m2t
